[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"
